[package]
name = "zap-model"
version = "0.1.1"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"
description = "Internal models for zap, a simple configuration management tool"
homepage = "https://github.com/rtyler/zap"
repository = "https://github.com/rtyler/zap"
license = "AGPL-3.0+"
keywords = ["sysadmin", "management"]

[dependencies]
handlebars = "~3.5"
log = "0.4"
pest = "~2.1"
pest_derive = "~2.1"
